### PR TITLE
Update vendor package Quality Declaration to QL3.

### PR DESCRIPTION
**Pull request by hidmic**
Precisely what the title says.

### CODE REVIEW

**Comment by nuclearsandwich** [comment]
As far as I can see, nothing has changed about foonathan_memory_vendor since the QD was last updated, but it was previously meeting the QL3 criteria and this update reflects that?

**Comment by hidmic** [comment]
> As far as I can see, nothing has changed about foonathan_memory_vendor since the QD was last updated, but it was previously meeting the QL3 criteria and this update reflects that?

AFAIU that is correct. A QL3 package can have a >QL3 dependency as per [REP-2004](https://ros.org/reps/rep-2004.html#quality-level-3).

**Comment by nuclearsandwich** [comment]
> A QL3 package can have a >QL3 dependency as per [REP-2004](https://ros.org/reps/rep-2004.html#quality-level-3).

I'm either confused about what the dependency relationship has to do with the change or I'm mistaken about the effect of this PR.

**Comment by hidmic** [comment]
> I'm either confused about what the dependency relationship has to do with the change or I'm mistaken about the effect of this PR.

Probably didn't provide enough information. My bad.

The `foonathan_memory_vendor` package is already QL3 according to REP-2004. I presume it was not marked as such before this patch either due to a misunderstanding about the requirements on its dependencies or, most likely, an omission.

Your initial assesment:

> nothing has changed about foonathan_memory_vendor since the QD was last updated, but it was previously meeting the QL3 criteria and this update reflects that?

is correct.

**Comment by nuclearsandwich** [comment]
Appreciate the clarification. That all makes sense to me.

**Review by nuclearsandwich — APPROVED** [review]

**Comment by nuclearsandwich** [comment]
Since this is a documentation-only change I don't see a need for CI.

**Pull request merged**
